brasileiro = ('Botafogo', 'Palmeiras', 'Bragantino', 'Grêmio', 'Flamengo', 'Atlético-MG', 'Atlético-PR', 'Fluminense', 'Fortaleza', 'Cuiabá', 'São Paulo', 'Internacional', 'Cruzeiro', 'Corinthians', 'Bahia', 'Santos', 'Goiás', 'Vasco da Gama','Coritiba', 'América-MG')
print("="*10,end="")
print(" 5 primeiros colocados ",end="")
print("="*10)
for c in range(0, 5):
    print("{}° {}".format(c+1, brasileiro[c]))
print("="*10,end="")
print(" 4 últimos colocados ",end="")
print("="*10)
for z in range(16, len(brasileiro)):
    print("{}° {}".format(z+1, brasileiro[z]))
print("="*10,end="")
print(" Ordem alfabética ",end="")
print("="*10)
print(sorted(brasileiro))
print("="*10,end="")
print(" Esporte Clube Bahia ",end="")
print("="*10)
print("{}° Bahia".format(brasileiro.index("Bahia")+1))
